services:
  app:
    image: hello-frontend-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which docker file to read
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say " the same location as the docke-compose.yml"
    ports:
      - 3000:3000
    container_name: hello-front-dev # This will name the container hello-front-dev